apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-cbxfdshz
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-cbxfdshz:cdbd78f6af7fb41e7d21e99b4e126d70e7dc9d84@sha256:06d6fb74f0b0e763c11d5a94e22ec4910c10170d286ef469d9d011a0941722b3
        name: container-image  
